services:
  # =============================
  # DATABASE
  # =============================
  db:
    image: postgres:17.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  # =============================
  # NATS SERVER
  # =============================
  nats-server:
    image: nats:2.11.0-alpine3.21
    ports:
      - "8222:8222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
    command: "-c /etc/nats/nats.conf"

  # =============================
  # MAFCS MS GATEWAY
  # =============================
  mafcs-ms-gateway:
    build:
      context: ./mafcs-ms-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "${MS_GATEWAY_PORT}:${MS_GATEWAY_PORT}"
      - "9230:9230"
    volumes:
      - ./mafcs-ms-gateway/src:/usr/src/app/src
      - /usr/src/app/node_modules
    command: npm run start:debug
    environment:
      - NATS_SERVER=nats://nats-server:4222
      - PORT=${MS_GATEWAY_PORT}
      - NODE_ENV=development

  # =============================
  # MAFCS MS AUTH
  # =============================
  mafcs-ms-auth:
    build:
      context: ./mafcs-ms-auth
      dockerfile: Dockerfile.dev
    ports:
      - "${MS_AUTH_PORT}:${MS_AUTH_PORT}"
      - "9231:9231"
    volumes:
      - ./mafcs-ms-auth/src:/usr/src/app/src
      - /usr/src/app/node_modules
    command: npm run start:debug
    environment:
      - NATS_SERVER=nats://nats-server:4222
      - PORT=${MS_AUTH_PORT}
      - NODE_ENV=development

volumes:
  mafcs-ms-gateway-node_modules:
  mafcs-ms-auth-node_modules:
